# Generated by Django 5.0.13 on 2025-12-02 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgenteSoporte',
            fields=[
                ('id_agente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('especialidad', models.CharField(max_length=100)),
                ('fecha_contratacion', models.DateField()),
                ('nivel_experiencia', models.CharField(max_length=50)),
                ('turno', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BaseConocimiento',
            fields=[
                ('id_articulo', models.AutoField(primary_key=True, serialize=False)),
                ('titulo_articulo', models.CharField(max_length=255)),
                ('contenido_articulo', models.TextField()),
                ('fecha_publicacion', models.DateTimeField()),
                ('autor', models.CharField(max_length=100)),
                ('categoria_articulo', models.CharField(max_length=50)),
                ('palabras_clave', models.TextField()),
                ('veces_consultado', models.IntegerField()),
                ('es_publico', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ClienteSoporte',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=255)),
                ('contacto_principal', models.CharField(max_length=100)),
                ('email_contacto', models.CharField(max_length=100)),
                ('telefono_contacto', models.CharField(max_length=20)),
                ('sector_empresa', models.CharField(max_length=100)),
                ('fecha_registro', models.DateField()),
                ('nivel_soporte', models.CharField(max_length=50)),
                ('sitio_web', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SLA',
            fields=[
                ('id_sla', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_sla', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('tiempo_respuesta_horas', models.IntegerField()),
                ('tiempo_resolucion_horas', models.IntegerField()),
                ('prioridad_asociada', models.CharField(max_length=20)),
                ('penalizacion_incumplimiento', models.TextField()),
                ('es_activo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TicketSoporte',
            fields=[
                ('id_ticket', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField()),
                ('estado', models.CharField(max_length=50)),
                ('prioridad', models.CharField(max_length=20)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('tipo_incidente', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=50)),
                ('resolucion', models.TextField(blank=True, null=True)),
                ('agente_asignado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.agentesoporte')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.clientesoporte')),
            ],
        ),
        migrations.CreateModel(
            name='SatisfaccionCliente',
            fields=[
                ('id_encuesta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_encuesta', models.DateTimeField()),
                ('calificacion_agente', models.IntegerField()),
                ('calificacion_resolucion', models.IntegerField()),
                ('comentarios_cliente', models.TextField(blank=True, null=True)),
                ('fecha_envio', models.DateTimeField()),
                ('fue_resuelto', models.BooleanField()),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.ticketsoporte')),
            ],
        ),
        migrations.CreateModel(
            name='Interaccion',
            fields=[
                ('id_interaccion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_interaccion', models.DateTimeField()),
                ('tipo_interaccion', models.CharField(max_length=50)),
                ('descripcion_interaccion', models.TextField()),
                ('archivos_adjuntos', models.TextField(blank=True, null=True)),
                ('duracion_minutos', models.IntegerField()),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.agentesoporte')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.ticketsoporte')),
            ],
        ),
    ]
